### ISSUE TITLE
Git Changelog plugin crashes on run

### ISSUE THREAD

**Issue by meyerkev** [paulwellnerbou/git-changelog-jenkins-plugin#7]
We're getting this every time we try to use this plugin, and can't figure out where changelog.mustache is stored on the server itself.  

---
--- Git Changelog ---
---
java.lang.RuntimeException: Cannot find on classpath (changelog.mustache) or filesystem (/opt/jenkins_slave/changelog.mustache).
	at se.bjurr.gitchangelog.api.GitChangelogApi.getTemplateContent(GitChangelogApi.java:502)
	at se.bjurr.gitchangelog.api.GitChangelogApi.render(GitChangelogApi.java:94)
	at se.bjurr.gitchangelog.api.GitChangelogApi.render(GitChangelogApi.java:123)
	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:151)
	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:29)
	at hudson.remoting.UserRequest.perform(UserRequest.java:210)
	at hudson.remoting.UserRequest.perform(UserRequest.java:53)
	at hudson.remoting.Request$2.run(Request.java:358)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: changelog.mustache (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.google.common.io.Files$1.getInput(Files.java:105)
	at com.google.common.io.Files$1.getInput(Files.java:102)
	at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:249)
	at com.google.common.io.Files.toByteArray(Files.java:197)
	at com.google.common.io.Files.toString(Files.java:223)
	at se.bjurr.gitchangelog.api.GitChangelogApi.getTemplateContent(GitChangelogApi.java:496)
	... 12 more

**Comment by paulwellnerbou** [comment]
That is part of @tomasbjerre's plugin part.
Please use https://github.com/jenkinsci/git-changelog-plugin and re-open the bug there, please.

**Comment by tomasbjerre** [comment]
Looks like you checked the "Show summary" checkbox but did not supply a template. It falls back on locking for a template in a file and that file is not found.
